[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.1"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
